import type { LegalContent } from "./types";

const legal: LegalContent = (site, cookie) => ({
  terms: {
    title: "Terms of Use",
    description: `The terms for using the ${site.name} CV builder.`,
    intro: [
      `These terms govern the use of the ${site.name} online CV builder (the “Service”). By using the Service, you accept these terms; if you do not agree with them, please do not use the Service.`,
    ],
    sections: [
      {
        id: "provider",
        title: "About the provider",
        blocks: [
          {
            list: [
              `Name: ${site.operator.name}`,
              `Registered address: ${site.operator.address}`,
              `Email: ${site.operator.email}`,
              `Registration number: ${site.operator.registry}`,
              `Tax number: ${site.operator.taxNumber}`,
            ],
          },
          `Hosting provider: ${site.hosting.name}, ${site.hosting.address}, ${site.hosting.website}`,
        ],
      },
      {
        id: "service",
        title: "The Service",
        blocks: [
          "The Service is a free, browser-based tool for writing CVs and downloading them as PDF files. Its main features are templates and design settings, a live preview, CVs in five languages, photo support, saving and loading JSON files, and a writing assistant that uses artificial intelligence (the “AI assistant”).",
          "No registration is required. Your CV data is stored by your browser and the PDF is created on your device; the provider has no access to this data. The only exception is the AI assistant, whose data processing is described in the Privacy Policy.",
        ],
      },
      {
        id: "acceptance",
        title: "Acceptance and scope",
        blocks: [
          "These terms become binding when you first use the Service and apply for as long as you use it. Using the Service creates a free agreement concluded electronically between you and the provider; the provider does not file it separately, and the terms are always available on this page.",
          "You must be at least 16 years old to use the Service; younger users may only use it with the consent of a parent or guardian.",
        ],
      },
      {
        id: "use",
        title: "Your obligations",
        blocks: [
          "You agree to",
          {
            list: [
              "use the Service for lawful purposes only;",
              "only use content (such as photos) that you have the right to use, and handle other people’s data lawfully;",
              "not overload or try to circumvent the limits of the Service – in particular, not send automated or mass requests to the AI assistant;",
              "not attempt to disrupt the Service or gain unauthorised access to the provider’s systems.",
            ],
          },
          "You alone are responsible for the content of your CV, its accuracy and how you use it.",
        ],
      },
      {
        id: "ai",
        title: "The AI assistant",
        blocks: [
          "At your explicit request (when you press its button), the AI assistant uses the Google Gemini service to suggest text for a field. A suggestion is never added to your CV without your approval.",
          "Text generated by artificial intelligence may be wrong, inaccurate or untrue. You must check every suggestion before accepting and using it; the provider accepts no responsibility for the content of suggestions.",
          "Do not enter special categories of personal data (such as health data) into the fields processed by the AI assistant, nor any third-party data that you are not entitled to share.",
          "Use of the AI assistant is subject to usage limits and depends on an external provider, so it may sometimes be slow or unavailable. The provider may change or discontinue this feature at any time.",
        ],
      },
      {
        id: "ip",
        title: "Intellectual property",
        blocks: [
          "The software, design, templates and texts of the Service are the intellectual property of the provider or its licensors. The embedded fonts are used under the SIL Open Font License.",
          "The content you enter belongs to you. You may use the finished PDF CV – including the template it uses – freely and without limitation for your own job search and professional purposes, with no fee and no attribution required.",
          "Copying, reselling or offering the Service or its templates as your own service without the provider’s permission is prohibited.",
        ],
      },
      {
        id: "data",
        title: "Your data and backups",
        blocks: [
          "Your CV data is stored only in your browser. It may be lost if you clear your browsing data, switch browser or device, or use private browsing. It is your responsibility to make backups with “Save to file”; the provider cannot recover lost data.",
        ],
      },
      {
        id: "liability",
        title: "Liability",
        blocks: [
          "The Service is provided as is and as available. The provider strives for continuous, error-free operation but does not guarantee it: maintenance, errors or outages of external providers (hosting, AI) may make the Service temporarily unavailable.",
          "To the extent permitted by law, the provider is not liable in particular for",
          {
            list: [
              "the outcome of job applications or other applications;",
              "the content and accuracy of your CV;",
              "the loss of data stored in your browser;",
              "the content of the AI assistant’s suggestions;",
              "damage resulting from faults of your device or internet connection.",
            ],
          },
          "This limitation does not apply to liability for intentional or grossly negligent breaches, for breaches causing harm to life, physical integrity or health, or to any other liability that cannot be excluded by law.",
        ],
      },
      {
        id: "fees",
        title: "Fees",
        blocks: [
          "The Service is currently entirely free of charge. If the provider introduces paid features in the future, it will announce their terms clearly in advance, and paid features can only be used with your explicit acceptance.",
        ],
      },
      {
        id: "changes",
        title: "Changes and termination",
        blocks: [
          "The provider may amend these terms. The amended terms will be published on this page with their effective date; continuing to use the Service after that date constitutes acceptance of the amended terms.",
          "The provider may change, suspend or discontinue the Service at any time. Because your CV data is in your browser, this does not affect it, and your JSON backup remains usable independently of the Service.",
        ],
      },
      {
        id: "law",
        title: "Governing law and complaints",
        blocks: [
          "These terms are governed by Hungarian law. If you are a consumer, this does not deprive you of the protection afforded by the mandatory consumer protection rules of the country where you habitually reside.",
          `For questions, complaints or feedback, contact the provider at ${site.operator.email}; you will receive a substantive reply within 30 days. Disputes are decided by the court with jurisdiction under the applicable law; consumers may also turn to the conciliation or alternative dispute resolution body competent for their place of residence.`,
          "These terms are available in several languages; in case of any discrepancy, the Hungarian version prevails.",
        ],
      },
    ],
  },

  privacy: {
    title: "Privacy Policy",
    description: `What data ${site.name} processes and what rights you have.`,
    intro: [
      `${site.name} is designed to process as little personal data as possible: no registration, no database, no analytics and no tracking. Based on the EU General Data Protection Regulation (GDPR), this policy explains what data is processed and what rights you have.`,
    ],
    sections: [
      {
        id: "controller",
        title: "The data controller",
        blocks: [
          {
            list: [`Name: ${site.operator.name}`, `Address: ${site.operator.address}`, `Email: ${site.operator.email}`],
          },
          "For any data protection matter, you can contact the controller (“we”) at the email address above.",
        ],
      },
      {
        id: "summary",
        title: "In short",
        blocks: [
          {
            list: [
              "Your CV data – including your photo – is stored only in your browser; we never receive or see it.",
              "The PDF is created on your device.",
              "The AI assistant only sends data when you press its button, and even then only the text of the field you are editing and your professional background – never your name, contact details, date of birth or photo.",
              "No registration, no analytics, no advertising or tracking cookies.",
            ],
          },
        ],
      },
      {
        id: "local",
        title: "Data stored in your browser",
        blocks: [
          "The Service saves your CV content, photo and design settings in your browser’s local storage (localStorage) so that your work is not lost. Apart from the AI assistant case described below, this data is not transmitted to us or to anyone else, so we do not process it.",
          "Your chosen colour theme (light or dark) is also kept in local storage. You can delete this data at any time with “File → New, empty CV” or by clearing your browser data.",
        ],
      },
      {
        id: "cookie",
        title: "Language preference (cookie)",
        blocks: [
          `When you switch language, the Service sets a cookie named “${cookie}” that stores the code of the chosen language (for example “en”) for up to one year, so that the site appears in the right language on your next visit. This cookie is strictly necessary for a feature you explicitly requested and cannot identify you, so it does not require consent. The Service uses no other cookies.`,
        ],
      },
      {
        id: "ai",
        title: "The AI assistant",
        blocks: [
          "When you use the AI assistant, the Service sends the following data to our server, which forwards it to the Google Gemini API:",
          {
            list: [
              "the current text of the field you are editing (profile or item description);",
              "your professional background: your job title, the names, organisations and dates of your entries, shortened descriptions, your skills and languages (when writing your profile, such a summary of your whole CV);",
              "the language of your CV and the requested action.",
            ],
          },
          "Your name, email address, phone number, city, website and profile links, date of birth and photo are never sent. However, if you type personal data into the field yourself, it is sent as part of the text.",
          "**Purpose:** creating the text suggestion you asked for. **Legal basis:** providing a service you explicitly requested (Article 6(1)(b) GDPR).",
          `**Retention:** we do not store or log the text; it exists in the server’s memory only until the response is complete. Google processes requests under the Gemini API terms: ${site.ai.terms}`,
          "Using the AI assistant is optional; every other feature of the Service works without it.",
        ],
      },
      {
        id: "logs",
        title: "Technical data and logs",
        blocks: [
          "When serving pages and processing AI assistant requests, the hosting provider’s servers record technical data (IP address, time, requested address, browser type) to keep the Service running and to prevent abuse. For AI assistant requests, the IP address is also kept in the server’s memory for up to 10 minutes so that excessive use can be limited.",
          "**Legal basis:** our legitimate interest in operating the Service securely (Article 6(1)(f) GDPR). **Retention:** for a short period, according to the hosting provider’s logging settings.",
        ],
      },
      {
        id: "contact",
        title: "Contacting us by email",
        blocks: [
          "If you email us, we process the data in your message (name, email address, content) to answer your enquiry, based on our legitimate interest (Article 6(1)(f) GDPR), for up to one year after the matter is closed.",
        ],
      },
      {
        id: "processors",
        title: "Processors and international transfers",
        blocks: [
          {
            list: [
              `${site.hosting.name} (${site.hosting.address}) – hosting and server infrastructure;`,
              `${site.ai.name} (${site.ai.address}) – the Gemini API, which produces the AI assistant’s suggestions.`,
            ],
          },
          "Both providers also process data in the United States. Transfers are based on the EU–US Data Privacy Framework and/or the standard contractual clauses adopted by the European Commission.",
          "We do not sell personal data, do not use it for marketing or profiling, and do not make automated decisions.",
        ],
      },
      {
        id: "rights",
        title: "Your rights",
        blocks: [
          "Under the GDPR, you may request access to your personal data, its rectification, erasure or the restriction of its processing, object to processing based on legitimate interest, and exercise your right to data portability. We respond to requests within one month at the latest.",
          "Because we do not store your CV data, you exercise these rights (for example erasure) for that data directly in your browser.",
          `If you have a complaint, you can contact the supervisory authority: ${site.authority.name}, ${site.authority.address}, ${site.authority.email}, ${site.authority.website}. You may also turn to the data protection authority of the EU country where you live or work, or to a court.`,
        ],
      },
      {
        id: "children",
        title: "Children",
        blocks: [
          "The Service is not specifically aimed at children under 16. Users under 16 may only use the AI assistant with the consent of a parent or guardian.",
        ],
      },
      {
        id: "security",
        title: "Security",
        blocks: [
          "The connection between the site and the server is encrypted (HTTPS), and API keys are stored only on the server. Because your CV data is on your device, protecting that device also protects your data (for example a screen lock, or clearing your browsing data on a shared computer).",
        ],
      },
      {
        id: "changes",
        title: "Changes to this policy",
        blocks: ["We may update this policy. The current version, with its effective date, is always available on this page."],
      },
    ],
  },
});

export default legal;
